// !!! This is a file automatically generated by hipify!!!
/*
 * Sparse Grid Sample API
 *
 * Copyright (C) 2025, Jianfeng XIANG <belljig@outlook.com>
 * All rights reserved.
 *
 * Licensed under The MIT License [see LICENSE for details]
 *
 * Written by Jianfeng XIANG
 */

#pragma once
#include "../../hip/grid_sample/grid_sample.h"
