[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "torch",
    "numpy",
    "plyfile",
    "trimesh",
    "tqdm",
    "zstandard",
    "easydict"
]
build-backend = "setuptools.build_meta"


[project]
name = "o_voxel"
version = "0.0.1+rocm"
description = "All about voxel (ROCm)"
requires-python = ">=3.8"
authors = [
    { name = "Jianfeng Xiang", email = "belljig@outlook.com" },
    { name = "Michael Lamothe", email = "michael.lamothe@gmail.com" }
]
dependencies = [
    "torch",
    "numpy",
    "plyfile",
    "trimesh",
    "tqdm",
    "zstandard",
    "easydict",
    "cumesh",
    "flex_gemm"
]
